runtime: nodejs

env: flex

beta_settings:
  cloud_sql_instances: dive-ios:us-central1:dive=tcp:3307

handlers:
- url: /
  static_files: client/dist/index.html
  upload: client/dist/index.html

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto